### PR TITLE
add faker-server

### PR DESCRIPTION
**Pull request by Ray-D-Song**
I added my personal project [faker-server](https://github.com/Ray-D-Song/faker-server).  
A self-hosted node.js mock server based on faker.js.  

image

### CODE REVIEW

**Review by ST-DDT — CHANGES_REQUESTED** [review]
The list is sorted alphabetically.
Please move your entry to the correct line.

**Comment by Ray-D-Song** [comment]
> The list is sorted alphabetically. Please move your entry to the correct line.

Okay, I have adjusted to the correct position

**Comment by ST-DDT** [comment]
Nice idea btw. I thought about/planned doing something similar a while ago, but I didnt have time for it yet.

The optional value list confuses me a bit.
Because it is used with alphaNumeric but to me it looks like a static value or to be used with helpers.arrayElement.
Or maybe i'm just confused about the purpose of the selection.

**Comment by Ray-D-Song** [comment]
> Nice idea btw. I thought about/planned doing something similar a while ago, but I didnt have time for it yet.
> 
> The optional value list confuses me a bit. Because it is used with alphaNumeric but to me it looks like a static value or to be used with helpers.arrayElement. Or maybe i'm just confused about the purpose of the selection.

I understand your confusion.
For example, I have a `/notice/list` API, which includes a `type` field. This is an enumerated value and can be one of `message`, `warn`, or `error`.
I hope to randomly select one of the three values mocked out. At this time, enter in the input box:
message^warn^error.

If you want the return value to be a specific value, such as code: 200, just enter 200.

So this actually represents a range of random values or a specific value, but I didn't know how to express it when developing. 😂

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
> So this actually represents a range of random values or a specific value, but I didn't know how to express it when developing. 😂

I would probably go for helpers.arrayElement then or maybe fake a faker method `static` that only has a single value.

**Review by Shinigami92 — APPROVED** [review]

**Review by xDivisionByZerox — APPROVED** [review]

**Pull request merged**
